### ISSUE TITLE
MX record points to IP address, some servers refuse to deliver mail to Lavaboom

### ISSUE THREAD

**Issue by flixi** [lavab/mailer#37]
https://github.com/lavab/web/issues/468

**Comment by andreis** [comment]
Changed our DNS records from

```
lavaboom.com.		1800 IN	MX 10 136.243.52.199.
```

to 

```
lavaboom.com.		1800 IN	MX 10 mx.lavaboom.com.
mx.lavaboom.com.		1717 IN	A 136.243.52.199
```

This should solve it. cc @pzduniak

**Comment by mlooz** [comment]
It fixed it for me. Server which complained yesterday now delivered mail without issue.
