### ISSUE TITLE
Redirect admin emails to team@lavaboom.com

### ISSUE THREAD

**Issue by andreis** [lavab/mailer#4]
Emails to:
* `hi`
* `admin`
* `webmaster`
* `support`
* `contact`
* `ceo`
* `hostmaster`

should be redirected to `team@lavaboom.com` and applied a label – the address they've been sent to.

Optionally, if we have nested labels support, `Admin`/`<email_address>` would be even better.

**Comment by pzduniak** [comment]
Please give me a list of what mapping should be done in https://trello.com/c/AljXyaA4/172-email-routing
