### ISSUE TITLE
Inbox threads are sorted by date of first message, should be date of last message

### ISSUE THREAD

**Issue by flixi** [lavab/mailer#40]
https://github.com/lavab/web/issues/479

**Comment by flixi** [comment]
![bildschirmfoto 2015-04-17 um 19 29 48](https://cloud.githubusercontent.com/assets/707993/7207251/4e475976-e538-11e4-9e42-89996ddb2f61.png)
On the hello Account it doesn't even show me any sent ones. @pzduniak

**Comment by let4be** [comment]
wow, this must be a _very_ old version of web @flixi 
New version looks different and has version right above logout button (0.2.6 currently)

**Comment by flixi** [comment]
It's the current master!

**Comment by let4be** [comment]
then we need to deploy... There are a lot of improvements in the recent 0.2.x versions

**Comment by let4be** [comment]
master is updated, but looks like not deployed

**Comment by pzduniak** [comment]
I deployed it, but I don't see the version.

**Comment by flixi** [comment]
Me neither.
