### ISSUE TITLE
Can't send text/plain email to lavaboom acc

### ISSUE THREAD

**Issue by let4be** [lavab/mailer#44]
When content is

`-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v0.10.1
Comment: http://openpgpjs.org

wcFMA3AwiwtJjuo+ARAAsw++Tuve/2TQxORF18sPFGYdA//AI5Gglaj2kmcK
4h9j6vH2njiauCaJQYU9TXtrUa1ZltYQ2SM3Iy2UkclWxGS91ESg187eyZpS
rgwwZ/kHtavzk9LFva5+sHlumskY5KLCcDBtl1zRZhNciwjCpce0TBq/AZlF
Z1UVr0jZmZ774K4Qr4tUyrB45g851mi+MkcbfJ4T3a9FprDVbYJKraHFrcDY
uDbA/L0zOfbQVWSwt8ia4QC+vkTA8HwnisbWzEI9nhkv0qZeb1PmZR4HqtFD
pT3T9R88vhnkGLalGvVswil5FdnkdgObUmZoVFKCMNoMq7p5y2EwsfTEylM1
5rB4zdDTBP0/f/hcoCuIoxVM+wg/wIWKx6RD9W6vLMYk7Dj+Pgevllv/BXaB
vGS8+vUx0urrk29JKqy9nE3otRh4jwcIZspsZTYFTacf+Q5dOwahWCXiFoDi
penOUYxiOxQzTe0b/tymdQYz97EoJRUnBOGh8S+EchtpAq6/FvntxQtCB6Kf
Z/HzJRiCT7GRcFfycg6nhUBbv1+nN3HF7nLC7bzoto1ud1R7prH5kkxUtCpa
A13aEcLJQBcLQ3I00wIBVUiT1O0wT7cXIm6OHn79ij4MFxpBL/v4zloXWykS
Ii02BinxDid+blWNaBTxjte7JCZ/qpV43ScCfy47XvnSrQHXezodzXUzTDn1
mf2jNa/wT0zLDF7VzDRDo73wG4fIj+RXQiSKBpS0wV6GOnP2/QDgIBDcFtAi
2sifEUT6QK0G0n6lpsR5j8ccjcPlOJQZ7B+sGYNe2ZN6JQ+9zaujtnA3oG1o
WUmWC/EmhHGLicqwyrFd8UVCt6N8dQvRQumjSvwSIAXZI50jciMqsjSUn2O1
UT3K72zsZlJvBQh2Qr8TbEFfJ2tq1LB77wGZ
=2vrG
-----END PGP MESSAGE-----`

email doesn't get delivered

**Comment by pzduniak** [comment]
https://trello.com/c/RA1TyH8D/170-spamc-crash

**Comment by pzduniak** [comment]
Please try again.

**Comment by let4be** [comment]
works
