### ISSUE TITLE
Something wrong with encoding

### ISSUE THREAD

**Issue by let4be** [lavab/mailer#46]
email text:
> Front-End d3év.

subject line:
> [Support] from Felix M=C3=BCller-Irion

Ideas?

**Comment by pzduniak** [comment]
I noticed that I'm using a wrong RFC for headers encoding. Will fix it tomorrow.

**Comment by pzduniak** [comment]
![Proof](http://qs.lc/pvg9y)

5c01beac70e20dd73777057a38e4bbf8fab2e4f4
