### ISSUE TITLE
PGP/Mime is broken

### ISSUE THREAD

**Issue by let4be** [lavab/mailer#58]
`GET /emails?thread=...`
returns an email with corrupted body that contains only
`Version: 1↵`

side question:
as threads.get/threads.list threads with pgp/mime does not contain manifests what should I display in the subject?

**Comment by let4be** [comment]
Still broken on api.lavaboom.io

threads/emails list return:
Manifest: "Version: 1↵"

Email list returns encrypted pgp envelope, but when I decrypt it I get smtp garbage
```
Content-Type: multipart/mixed; boundary="BGSu6qQWJAgBomNDVjk5if6CPDufW7IT5"

--BGSu6qQWJAgBomNDVjk5if6CPDufW7IT5
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Heya!

--BGSu6qQWJAgBomNDVjk5if6CPDufW7IT5--
```

**Comment by pzduniak** [comment]
It's not garbage, it's what you have to parse :)
